export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const USERS_SERVICE = 'USERS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const COMPANIES_REPOSITORY = 'COMPANIES_REPOSITORY';
export const COMPANIES_SERVICE = 'COMPANIES_SERVICE';
export const CAMPAIGNS_REPOSITORY = 'CAMPAIGNS_REPOSITORY';
export const CAMPAIGNS_SERVICE = 'CAMPAIGNS_SERVICE';
